site_name: HEXRDGUI Documentation
theme:
  name: material
  logo: img/hexrd_logo.png
  favicon: img/hexrd_logo.png
  palette:
    primary: 'light blue'
    accent: 'light blue'
markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - codehilite
copyright: '<font color=#666>Content is available under </font><a href="https://creativecommons.org/licenses/by/4.0/" title="CC-BY 4.0">CC-BY 4.0</a></font>'
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
extra_css:
  - 'stylesheets/extra.css'
nav:
  - index.md
  - installing.md
  - Configuration:
    - configuration/instrument.md
    - configuration/images.md
    - configuration/materials.md
    - configuration/overlays.md
    - configuration/state.md
  - views.md
  - Calibration:
    - calibration/fast_powder.md
    - calibration/composite_laue_and_powder.md
    - calibration/rotation_series.md
    - calibration/wppf.md
  - HEDM Workflow:
    - hedm/indexing.md
    - hedm/fit_grains.md
  - contributing.md
